spring:
  application:
    name: pulseboard
  kafka:
    bootstrap-servers: localhost:19092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: pulseboard-consumer-group
      # Wrap to let DefaultErrorHandler handle deserialization failures
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        # Delegate to actual deserializers
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        # Tell JsonDeserializer what class to target when there are no type headers            
        spring.json.value.default.type: "com.pulseboard.core.Event"
        spring.json.add.type.headers: false
        spring.json.trusted.packages: "com.pulseboard.core"
      enable-auto-commit: false
    listener:
      ack-mode: manual
    topics:
      events: "events"
      alerts: "alerts"

server:
  port: 8080

# CORS configuration to allow frontend access
management:
  endpoints:
    web:
      cors:
        allowed-origins: "http://localhost:5173"
        allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
        allowed-headers: "*"

# Custom CORS for application endpoints
cors:
  allowed-origins: "http://localhost:5173"

# Transport configuration
transport:
  mode: kafka  # memory | kafka
