spring:
  application:
    name: pulseboard
  kafka:
    bootstrap-servers: localhost:19092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: pulseboard-consumer-group
      # Wrap to let DefaultErrorHandler handle deserialization failures
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        # Delegate to actual deserializers
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        # Tell JsonDeserializer what class to target when there are no type headers            
        spring.json.value.default.type: "com.pulseboard.core.EntityEvent"
        spring.json.add.type.headers: false
        spring.json.trusted.packages: "com.pulseboard.core"
      enable-auto-commit: false
    listener:
      ack-mode: manual
    topics:
      events: "events"
      cdp-events: "cdp-events"
      alerts: "alerts"

server:
  port: 8080

# CORS configuration to allow frontend access
management:
  endpoints:
    web:
      cors:
        allowed-origins: "http://localhost:5173"
        allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
        allowed-headers: "*"

# Custom CORS for application endpoints
cors:
  allowed-origins: "http://localhost:5173"

# Transport configuration
transport:
  mode: kafka  # memory | kafka

# Window Store configuration
window-store:
  # Time window size in minutes for aggregating events
  default-size: 5m
  # Maximum number of events to cache in memory
  max-cache-size: 10000
  # Time after which events expire from the cache
  cache-expiration: 10m

# Event Processor configuration
event-processor:
  # Time window size for processing events
  window-size: 5s
  # Grace period for processing late events
  grace-period: 2m
  # Time to live for deduplication of events
  dedup-ttl: 10m
  # Each tick is an interval for processing a batch of events
  ticker-interval: 1s

# Rolling Counter configuration
rolling-counter:
  # Size of the rolling window
  window-size: 24h
  # Size of each bucket in the rolling window
  bucket-size: 1m

# Segment Engine configuration
segment-engine:
  # Threshold of inactivity to re-engage segments
  reengage-inactivity-threshold: 10m
  # Threshold of event count to classify a user as a power user
  power-user-threshold: 5
  # Time window to evaluate power user status
  power-user-window: 24h
  
  
